#############################################################################
# Makefile for building: Gomoku
# Generated by qmake (2.01a) (Qt 4.3.2) on: jeu. janv. 3 22:33:54 2008
# Project:  Gomoku.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Gomoku.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Igomoku_core -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Button.cpp \
		Main.cpp \
		Mainwindow.cpp \
		OptionsWindow.cpp \
		gomoku_core/gomoku.cpp \
		gomoku_core/IA_alphabeta.cpp \
		gomoku_core/IA_negamax.cpp \
		gomoku_core/Move.cpp moc_Button.cpp \
		moc_Mainwindow.cpp \
		moc_OptionsWindow.cpp
OBJECTS       = Button.o \
		Main.o \
		Mainwindow.o \
		OptionsWindow.o \
		gomoku.o \
		IA_alphabeta.o \
		IA_negamax.o \
		Move.o \
		moc_Button.o \
		moc_Mainwindow.o \
		moc_OptionsWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Gomoku.pro
QMAKE_TARGET  = Gomoku
DESTDIR       = 
TARGET        = Gomoku

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gomoku.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile Gomoku.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Gomoku.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Gomoku1.0.0 || $(MKDIR) .tmp/Gomoku1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Gomoku1.0.0/ && $(COPY_FILE) --parents AlgorithmType.h Button.h ButtonState.h Mainwindow.h OptionsWindow.h gomoku_core/defines.h gomoku_core/gomoku.h gomoku_core/IA.h gomoku_core/IA_alphabeta.h gomoku_core/IA_negamax.h gomoku_core/Move.h Images/red.xpm Images/cyan.xpm Images/white.xpm Images/valid.xpm Images/cancel.xpm .tmp/Gomoku1.0.0/ && $(COPY_FILE) --parents Button.cpp Main.cpp Mainwindow.cpp OptionsWindow.cpp gomoku_core/gomoku.cpp gomoku_core/IA_alphabeta.cpp gomoku_core/IA_negamax.cpp gomoku_core/Move.cpp .tmp/Gomoku1.0.0/ && (cd `dirname .tmp/Gomoku1.0.0` && $(TAR) Gomoku1.0.0.tar Gomoku1.0.0 && $(COMPRESS) Gomoku1.0.0.tar) && $(MOVE) `dirname .tmp/Gomoku1.0.0`/Gomoku1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Gomoku1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Button.cpp moc_Mainwindow.cpp moc_OptionsWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Button.cpp moc_Mainwindow.cpp moc_OptionsWindow.cpp
moc_Button.cpp: ButtonState.h \
		Button.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Button.h -o moc_Button.cpp

moc_Mainwindow.cpp: Button.h \
		ButtonState.h \
		AlgorithmType.h \
		OptionsWindow.h \
		Mainwindow.h \
		Mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Mainwindow.h -o moc_Mainwindow.cpp

moc_OptionsWindow.cpp: AlgorithmType.h \
		Mainwindow.h \
		Button.h \
		ButtonState.h \
		OptionsWindow.h \
		OptionsWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) OptionsWindow.h -o moc_OptionsWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Button.o: Button.cpp Button.h \
		ButtonState.h \
		Images/red.xpm \
		Images/cyan.xpm \
		Images/white.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Button.o Button.cpp

Main.o: Main.cpp Mainwindow.h \
		Button.h \
		ButtonState.h \
		AlgorithmType.h \
		OptionsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

Mainwindow.o: Mainwindow.cpp Mainwindow.h \
		Button.h \
		ButtonState.h \
		AlgorithmType.h \
		OptionsWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mainwindow.o Mainwindow.cpp

OptionsWindow.o: OptionsWindow.cpp Images/valid.xpm \
		Images/cancel.xpm \
		OptionsWindow.h \
		AlgorithmType.h \
		Mainwindow.h \
		Button.h \
		ButtonState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptionsWindow.o OptionsWindow.cpp

gomoku.o: gomoku_core/gomoku.cpp gomoku_core/gomoku.h \
		gomoku_core/Move.h \
		gomoku_core/defines.h \
		Button.h \
		ButtonState.h \
		AlgorithmType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gomoku.o gomoku_core/gomoku.cpp

IA_alphabeta.o: gomoku_core/IA_alphabeta.cpp gomoku_core/IA_alphabeta.h \
		gomoku_core/defines.h \
		gomoku_core/gomoku.h \
		gomoku_core/Move.h \
		Button.h \
		ButtonState.h \
		AlgorithmType.h \
		gomoku_core/IA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IA_alphabeta.o gomoku_core/IA_alphabeta.cpp

IA_negamax.o: gomoku_core/IA_negamax.cpp gomoku_core/IA_negamax.h \
		gomoku_core/defines.h \
		gomoku_core/gomoku.h \
		gomoku_core/Move.h \
		Button.h \
		ButtonState.h \
		AlgorithmType.h \
		gomoku_core/IA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IA_negamax.o gomoku_core/IA_negamax.cpp

Move.o: gomoku_core/Move.cpp gomoku_core/Move.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Move.o gomoku_core/Move.cpp

moc_Button.o: moc_Button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Button.o moc_Button.cpp

moc_Mainwindow.o: moc_Mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Mainwindow.o moc_Mainwindow.cpp

moc_OptionsWindow.o: moc_OptionsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OptionsWindow.o moc_OptionsWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

